// Copyright (C) 2017 by bodguy
// This code is licensed under Apache 2.0 license (see LICENSE.md for details)

#ifndef TheodoreEngine_h
#define TheodoreEngine_h

#include "Asset/Asset.h"
#include "Asset/AssetManager.h"
#include "Asset/Font.h"
#include "Asset/GlyphInfo.h"
#include "Asset/Mesh.h"
#include "Asset/MeshGroup.h"
#include "Asset/MSAATexture2D.h"
#include "Asset/Pipeline.h"
#include "Asset/Shader.h"
#include "Asset/Texture.h"
#include "Asset/Texture2D.h"
#include "Asset/TextureCube.h"
#include "Asset/TextureOption.h"
#include "Asset/Vertex.h"
#include "Asset/WaveFrontObjMesh.h"

#include "Component/Collider/BoxCollider.h"
#include "Component/Collider/SphereCollider.h"
#include "Component/Collider//Collider.h"
#include "Component/Physics/Physics.h"
#include "Component/Physics/RaycastHit.h"
#include "Component/Physics/RigidBody2D.h"
#include "Component/BoneWeight.h"
#include "Component/Camera.h"
#include "Component/Component.h"
#include "Component/CubemapRenderer.h"
#include "Component/FontRenderer.h"
#include "Component/Gizmo.h"
#include "Component/KeyFrame.h"
#include "Component/Light.h"
#include "Component/Material.h"
#include "Component/MeshRenderer.h"
#include "Component/Renderer.h"
#include "Component/SkinnedMeshRenderer.h"
#include "Component/Sprite.h"
#include "Component/SpriteRenderer.h"
#include "Component/Transform.h"

#include "Core/Application.h"
#include "Core/GameObject.h"
#include "Core/Message.h"
#include "Core/Object.h"
#include "Core/Scene.h"
#include "Core/SceneManager.h"
#include "Core/ShaderManager.h"
#include "Core/TagManager.h"
#include "Core/UniqueId.h"

#include "Geometry/Bounds.h"
#include "Geometry/Plane.h"
#include "Geometry/Ray.h"

#include "Graphics/Enumeration.h"
#include "Graphics/FrameBuffer.h"
#include "Graphics/GPUBuffer.h"
#include "Graphics/Graphics.h"
#include "Graphics/InputStream.h"
#include "Graphics/RenderBuffer.h"
#include "Graphics/VertexArray.h"

#include "Helper/Bitmap.h"
#include "Helper/DataStream.h"
#include "Helper/Debug.h"
#include "Helper/File.h"
#include "Helper/ShapeGenerator.h"
#include "Helper/StringUtil.h"
#include "Helper/Utility.h"

#include "Math/Color.h"
#include "Math/Mathf.h"
#include "Math/Matrix4x4.h"
#include "Math/Quaternion.h"
#include "Math/Random.h"
#include "Math/Rect.h"
#include "Math/Vector2d.h"
#include "Math/Vector3d.h"
#include "Math/Vector4d.h"

#include "Platform/Input.h"
#include "Platform/Platform.h"
#include "Platform/Time.h"

using namespace Theodore;

#endif /* TheodoreEngine_h */
